# Example: Sync secret from AWS Secrets Manager to Kubernetes Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: backend-team
spec:
  # Refresh interval
  refreshInterval: 1h

  # Reference to ClusterSecretStore
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  # Target Kubernetes Secret
  target:
    name: database-credentials
    creationPolicy: Owner

  # Data to sync from AWS Secrets Manager
  data:
    - secretKey: username
      remoteRef:
        key: eks/production/database/credentials  # Path in Secrets Manager
        property: username  # JSON field in the secret

    - secretKey: password
      remoteRef:
        key: eks/production/database/credentials
        property: password

    - secretKey: host
      remoteRef:
        key: eks/production/database/credentials
        property: host

    - secretKey: port
      remoteRef:
        key: eks/production/database/credentials
        property: port
