apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: external-secrets-operator
spec:
  schema:
    apiVersion: v1alpha1
    kind: ExternalSecretsOperator
    group: secrets.company.com
    spec:
      # Cluster Configuration
      clusterName: string | required=true
      region: string | required=true
      accountID: string | required=true

      # Operator Configuration
      operatorNamespace: string | default="external-secrets-system"
      syncInterval: string | default="1h"

      # AWS Secrets Manager Configuration
      secretsPrefix: string | default="eks"  # Prefix for secrets path
      enableSecretsManager: boolean | default=true
      enableParameterStore: boolean | default=false

      # Resource Configuration
      cpuRequest: string | default="100m"
      memoryRequest: string | default="128Mi"
      cpuLimit: string | default="500m"
      memoryLimit: string | default="512Mi"

  resources:
    # Namespace
    - id: operatorNamespace
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: ${schema.spec.operatorNamespace}
          labels:
            app.kubernetes.io/name: external-secrets
            app.kubernetes.io/managed-by: kro

    # IAM Policy for External Secrets Operator
    - id: esoIAMPolicy
      template:
        apiVersion: iam.services.k8s.aws/v1alpha1
        kind: Policy
        metadata:
          name: external-secrets-operator-policy
          namespace: ${schema.spec.operatorNamespace}
        spec:
          name: "${schema.spec.clusterName}-external-secrets-operator-policy"
          description: "IAM policy for External Secrets Operator to access AWS Secrets Manager and SSM"
          policyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {{- if .spec.enableSecretsManager }}
                {
                  "Effect": "Allow",
                  "Action": [
                    "secretsmanager:GetSecretValue",
                    "secretsmanager:DescribeSecret",
                    "secretsmanager:ListSecrets"
                  ],
                  "Resource": "arn:aws:secretsmanager:${schema.spec.region}:${schema.spec.accountID}:secret:{{ .spec.secretsPrefix }}/*"
                },
                {{- end }}
                {{- if .spec.enableParameterStore }}
                {
                  "Effect": "Allow",
                  "Action": [
                    "ssm:GetParameter",
                    "ssm:GetParameters",
                    "ssm:GetParametersByPath"
                  ],
                  "Resource": "arn:aws:ssm:${schema.spec.region}:${schema.spec.accountID}:parameter/{{ .spec.secretsPrefix }}/*"
                },
                {{- end }}
                {
                  "Effect": "Allow",
                  "Action": ["kms:Decrypt"],
                  "Resource": "*",
                  "Condition": {
                    "StringEquals": {
                      "kms:ViaService": [
                        "secretsmanager.${schema.spec.region}.amazonaws.com",
                        "ssm.${schema.spec.region}.amazonaws.com"
                      ]
                    }
                  }
                }
              ]
            }

    # IAM Role for External Secrets Operator
    - id: esoIAMRole
      template:
        apiVersion: iam.services.k8s.aws/v1alpha1
        kind: Role
        metadata:
          name: external-secrets-operator-role
          namespace: ${schema.spec.operatorNamespace}
        spec:
          name: "${schema.spec.clusterName}-external-secrets-operator-role"
          description: "IAM role for External Secrets Operator"
          assumeRolePolicyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Service": "pods.eks.amazonaws.com"
                  },
                  "Action": [
                    "sts:AssumeRole",
                    "sts:TagSession"
                  ]
                }
              ]
            }
          policies:
            - "$resource: esoIAMPolicy.status.arn"

    # Pod Identity Association
    - id: esoPodIdentity
      template:
        apiVersion: eks.services.k8s.aws/v1alpha1
        kind: PodIdentityAssociation
        metadata:
          name: external-secrets-operator-pod-identity
          namespace: ${schema.spec.operatorNamespace}
        spec:
          clusterName: ${schema.spec.clusterName}
          namespace: ${schema.spec.operatorNamespace}
          serviceAccount: external-secrets
          roleARN: "$resource: esoIAMRole.status.ackResourceMetadata.arn"

    # ServiceAccount for External Secrets Operator
    - id: esoServiceAccount
      template:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: external-secrets
          namespace: ${schema.spec.operatorNamespace}
          annotations:
            eks.amazonaws.com/role-arn: "$resource: esoIAMRole.status.ackResourceMetadata.arn"

    # RBAC - ClusterRoleBinding for ESO controller
    - id: esoClusterRoleBinding
      template:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: external-secrets-controller
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: external-secrets-controller
        subjects:
          - kind: ServiceAccount
            name: external-secrets
            namespace: ${schema.spec.operatorNamespace}

    # Deployment for External Secrets Operator
    - id: esoDeployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: external-secrets-operator
          namespace: ${schema.spec.operatorNamespace}
          labels:
            app.kubernetes.io/name: external-secrets
            app.kubernetes.io/component: controller
        spec:
          replicas: 2
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxUnavailable: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: external-secrets
              app.kubernetes.io/component: controller
          template:
            metadata:
              labels:
                app.kubernetes.io/name: external-secrets
                app.kubernetes.io/component: controller
            spec:
              serviceAccountName: external-secrets
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                fsGroup: 1000
              containers:
                - name: external-secrets
                  image: ghcr.io/external-secrets/external-secrets:v0.12.1
                  imagePullPolicy: IfNotPresent
                  args:
                    - --concurrent=1
                    - --metrics-addr=:8080
                  ports:
                    - containerPort: 8080
                      name: metrics
                      protocol: TCP
                  resources:
                    requests:
                      cpu: ${schema.spec.cpuRequest}
                      memory: ${schema.spec.memoryRequest}
                    limits:
                      cpu: ${schema.spec.cpuLimit}
                      memory: ${schema.spec.memoryLimit}
                  securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities:
                      drop:
                        - ALL

    # ClusterSecretStore for AWS Secrets Manager
    - id: clusterSecretStore
      template:
        apiVersion: external-secrets.io/v1
        kind: ClusterSecretStore
        metadata:
          name: aws-secrets-manager
        spec:
          provider:
            aws:
              service: SecretsManager
              region: ${schema.spec.region}
              auth:
                jwt:
                  serviceAccountRef:
                    name: external-secrets
                    namespace: ${schema.spec.operatorNamespace}

    # ClusterSecretStore for AWS Parameter Store
    - id: clusterSecretStoreSSM
      template:
        apiVersion: external-secrets.io/v1
        kind: ClusterSecretStore
        metadata:
          name: aws-parameter-store
        spec:
          provider:
            aws:
              service: ParameterStore
              region: ${schema.spec.region}
              auth:
                jwt:
                  serviceAccountRef:
                    name: external-secrets
                    namespace: ${schema.spec.operatorNamespace}

    # Service for Metrics
    - id: esoService
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: external-secrets-operator-metrics
          namespace: ${schema.spec.operatorNamespace}
          labels:
            app.kubernetes.io/name: external-secrets
            app.kubernetes.io/component: controller
        spec:
          type: ClusterIP
          ports:
            - port: 8080
              targetPort: metrics
              protocol: TCP
              name: metrics
          selector:
            app.kubernetes.io/name: external-secrets
            app.kubernetes.io/component: controller

    # PodDisruptionBudget
    - id: esoPDB
      template:
        apiVersion: policy/v1
        kind: PodDisruptionBudget
        metadata:
          name: external-secrets-operator
          namespace: ${schema.spec.operatorNamespace}
        spec:
          minAvailable: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: external-secrets
              app.kubernetes.io/component: controller

