# TODO: Update repoURL with your actual GitHub repository URL (appears in 2 places below)
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-clusters
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/YOUR_ORG/YOUR_REPO
        revision: main
        directories:
          - path: observability/examples/clusters/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/YOUR_ORG/YOUR_REPO
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      # Health checks for ObservabilityCluster resources
      ignoreDifferences:
        - group: observability.company.com
          kind: ObservabilityCluster
          jsonPointers:
            - /status
