apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-platform
  namespace: argocd
spec:
  project: default
  source:
    # TODO: Update with your actual GitHub repository URL
    repoURL: https://github.com/YOUR_ORG/YOUR_REPO
    targetRevision: main
    path: observability/examples/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
