apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: external-dns-cluster
spec:
  schema:
    apiVersion: v1alpha1
    kind: ExternalDNSCluster
    group: externaldns.company.com
    spec:
      clusterName: string | required=true
      region: string | required=true
      accountID: string | required=true
      hostedZoneID: string | required=true
      domainFilter: string | required=true
      zoneType: string | default="public"
      policy: string | default="upsert-only"
      txtOwnerID: string

  resources:
    # Namespace - Dedicated namespace for ExternalDNS
    - id: externalDNSNamespace
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: external-dns-system
          labels:
            name: external-dns-system

    # ServiceAccount - No IRSA annotations (using Pod Identity instead)
    - id: externalDNSServiceAccount
      template:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: external-dns
          namespace: external-dns-system

    # IAM Policy - Permissions for ExternalDNS to manage Route53
    - id: externalDNSIAMPolicy
      template:
        apiVersion: iam.services.k8s.aws/v1alpha1
        kind: Policy
        metadata:
          name: external-dns-route53-policy
          namespace: external-dns-system
        spec:
          name: ExternalDNSRoute53Policy
          description: "IAM policy for ExternalDNS to manage Route53 records"
          policyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "route53:ChangeResourceRecordSets"
                  ],
                  "Resource": [
                    "arn:aws:route53:::hostedzone/${schema.spec.hostedZoneID}"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "route53:ListHostedZones",
                    "route53:ListResourceRecordSets"
                  ],
                  "Resource": "*"
                }{{- if eq .spec.zoneType "private" }},
                {
                  "Effect": "Allow",
                  "Action": [
                    "ec2:DescribeVpcs"
                  ],
                  "Resource": "*"
                }
                {{- end }}
              ]
            }

    # IAM Role - With Pod Identity trust policy
    - id: externalDNSIAMRole
      template:
        apiVersion: iam.services.k8s.aws/v1alpha1
        kind: Role
        metadata:
          name: external-dns-role
          namespace: external-dns-system
        spec:
          name: ExternalDNSRole
          description: "IAM role for ExternalDNS with Route53 permissions"
          assumeRolePolicyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Service": "pods.eks.amazonaws.com"
                  },
                  "Action": [
                    "sts:AssumeRole",
                    "sts:TagSession"
                  ]
                }
              ]
            }
          policies:
            - "arn:aws:iam::${schema.spec.accountID}:policy/ExternalDNSRoute53Policy"

    # Pod Identity Association - Links ServiceAccount to IAM Role
    - id: externalDNSPodIdentity
      template:
        apiVersion: eks.services.k8s.aws/v1alpha1
        kind: PodIdentityAssociation
        metadata:
          name: external-dns-pod-identity
          namespace: external-dns-system
        spec:
          clusterName: ${schema.spec.clusterName}
          namespace: external-dns-system
          serviceAccount: external-dns
          roleARN: "arn:aws:iam::${schema.spec.accountID}:role/ExternalDNSRole"

    # ClusterRole - RBAC permissions for ExternalDNS
    - id: externalDNSClusterRole
      template:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: external-dns
        rules:
          - apiGroups: [""]
            resources:
              - services
              - endpoints
              - pods
              - nodes
            verbs: ["get", "watch", "list"]
          - apiGroups: ["extensions", "networking.k8s.io"]
            resources:
              - ingresses
            verbs: ["get", "watch", "list"]
          - apiGroups: [""]
            resources:
              - namespaces
            verbs: ["get", "watch", "list"]

    # ClusterRoleBinding - Binds ClusterRole to ServiceAccount
    - id: externalDNSClusterRoleBinding
      template:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: external-dns
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: external-dns
        subjects:
          - kind: ServiceAccount
            name: external-dns
            namespace: external-dns-system

    # Deployment - ExternalDNS controller
    - id: externalDNSDeployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: external-dns
          namespace: external-dns-system
          labels:
            app: external-dns
        spec:
          replicas: 2
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 1
          selector:
            matchLabels:
              app: external-dns
          template:
            metadata:
              labels:
                app: external-dns
            spec:
              serviceAccountName: external-dns
              securityContext:
                fsGroup: 65534
                runAsNonRoot: true
                runAsUser: 65534
              containers:
                - name: external-dns
                  image: registry.k8s.io/external-dns/external-dns:v0.14.0
                  args:
                    - --source=service
                    - --source=ingress
                    - --domain-filter=${schema.spec.domainFilter}
                    - --provider=aws
                    - --policy=${schema.spec.policy}
                    - --aws-zone-type=${schema.spec.zoneType}
                    - --registry=txt
                    - --txt-owner-id=${schema.spec.clusterName}
                    - --txt-prefix=external-dns-
                    - --interval=1m
                    - --log-level=info
                    - --log-format=text
                  ports:
                    - name: http
                      containerPort: 7979
                      protocol: TCP
                  env:
                    - name: AWS_DEFAULT_REGION
                      value: ${schema.spec.region}
                    - name: AWS_REGION
                      value: ${schema.spec.region}
                  securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities:
                      drop: ["ALL"]
                  resources:
                    requests:
                      memory: "128Mi"
                      cpu: "100m"
                    limits:
                      memory: "512Mi"
                      cpu: "500m"
                  livenessProbe:
                    httpGet:
                      path: /healthz
                      port: 7979
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    timeoutSeconds: 5
                    failureThreshold: 3
                  readinessProbe:
                    httpGet:
                      path: /healthz
                      port: 7979
                    initialDelaySeconds: 5
                    periodSeconds: 10
                    timeoutSeconds: 5
                    failureThreshold: 3

    # Service - Exposes metrics endpoint for Prometheus scraping
    - id: externalDNSService
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: external-dns
          namespace: external-dns-system
          labels:
            app: external-dns
        spec:
          type: ClusterIP
          ports:
            - name: http
              port: 7979
              targetPort: 7979
              protocol: TCP
          selector:
            app: external-dns

    # PodDisruptionBudget - Ensures at least 1 replica during disruptions
    - id: externalDNSPDB
      template:
        apiVersion: policy/v1
        kind: PodDisruptionBudget
        metadata:
          name: external-dns
          namespace: external-dns-system
        spec:
          minAvailable: 1
          selector:
            matchLabels:
              app: external-dns
