apiVersion: platform.company.com/v1alpha1
kind: EKSPlatformFoundation
metadata:
  name: production
spec:
  clusterName: <YOUR_CLUSTER_NAME>  # e.g., production-cluster
  region: <YOUR_AWS_REGION>  # e.g., us-east-1
  accountID: "<YOUR_AWS_ACCOUNT_ID>"  # e.g., "123456789012"
  profile: production

  modules:
    observability: true
    dns: true
    compute: true
    metrics: true
    secrets: true
    logging: true

  observability:
    ampWorkspaceID: <YOUR_AMP_WORKSPACE_ID>  # e.g., ws-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    ampRemoteWriteEndpoint: <YOUR_AMP_REMOTE_WRITE_ENDPOINT>  # e.g., https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-xxx/api/v1/remote_write

  dns:
    hostedZoneID: <YOUR_HOSTED_ZONE_ID>  # e.g., Z0123456789ABCDEF
    domainFilter: <YOUR_DOMAIN>  # e.g., platform.example.com

  compute:
    spotEnabled: true
    consolidationPolicy: WhenEmptyOrUnderutilized
