apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: <YOUR_GIT_REPO_URL>       # e.g., https://github.com/your-org/eks-platform-blueprints
    targetRevision: main
    path: argocd
    directory:
      recurse: true
      include: '*.yaml'
      exclude: 'README.md'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
