apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: gpu-nodepool
spec:
  schema:
    apiVersion: v1alpha1
    kind: GPUNodePool
    group: ai.company.com
    spec:
      clusterName: string | required=true
      nodePoolName: string | default="gpu-general"
      acceleratorType: string | default="nvidia-gpu"  # nvidia-gpu, aws-neuron
      capacityType: string | default="on-demand"  # on-demand, spot
      cpuLimit: string | default="100"
      memoryLimit: string | default="400Gi"
      gpuLimit: string | default="8"

  resources:
    - id: gpuNodePool
      template:
        apiVersion: karpenter.sh/v1
        kind: NodePool
        metadata:
          name: ${schema.spec.nodePoolName}
        spec:
          template:
            metadata:
              labels:
                nodepool: ${schema.spec.nodePoolName}
                accelerator: ${schema.spec.acceleratorType}
            spec:
              requirements:
                - key: karpenter.sh/capacity-type
                  operator: In
                  values:
                    - ${schema.spec.capacityType}
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
              nodeClassRef:
                group: eks.amazonaws.com
                kind: NodeClass
                name: default
              taints:
                - key: nvidia.com/gpu
                  value: "true"
                  effect: NoSchedule
          limits:
            cpu: ${schema.spec.cpuLimit}
            memory: ${schema.spec.memoryLimit}
          disruption:
            consolidationPolicy: WhenEmpty
            consolidateAfter: 30s
            budgets:
              - nodes: "0"
