apiVersion: platform.company.com/v1alpha1
kind: EKSPlatformFoundation
metadata:
  name: full
spec:
  # Core configuration (REQUIRED - update these values)
  clusterName: <YOUR_CLUSTER_NAME>          # e.g., production
  region: <YOUR_AWS_REGION>                  # e.g., us-west-2
  accountID: "<YOUR_AWS_ACCOUNT_ID>"         # e.g., "123456789012"

  # Platform profile
  profile: production  # or staging, development

  # All modules enabled
  modules:
    observability: true
    dns: true
    compute: true
    metrics: true
    secrets: true
    logging: true

  # Observability (REQUIRED when observability module enabled)
  observability:
    ampWorkspaceID: <YOUR_AMP_WORKSPACE_ID>
    ampRemoteWriteEndpoint: https://aps-workspaces.<YOUR_AWS_REGION>.amazonaws.com/workspaces/<YOUR_AMP_WORKSPACE_ID>/api/v1/remote_write
    retentionDays: 30

  # DNS (REQUIRED when dns module enabled)
  dns:
    hostedZoneID: <YOUR_HOSTED_ZONE_ID>
    domainFilter: <YOUR_DOMAIN>              # e.g., prod.example.com
    zoneType: public
    policy: sync

  # Compute
  compute:
    spotEnabled: true
    computeOptimized: true
    memoryOptimized: true
    armGraviton: false

  # Metrics
  metrics:
    highAvailability: true

  # Secrets
  secrets:
    secretsPrefix: "<YOUR_SECRETS_PREFIX>"   # e.g., "eks/production"
    enableSecretsManager: true
    enableParameterStore: false
    syncInterval: "1h"

  # Logging
  logging:
    destination: cloudwatch
    retentionDays: 30
    logGroups:
      application: true
      dataplane: true
      audit: true
