apiVersion: platform.company.com/v1alpha1
kind: EKSPlatformFoundation
metadata:
  name: minimal
spec:
  # Core configuration (REQUIRED - update these values)
  clusterName: <YOUR_CLUSTER_NAME>          # e.g., development
  region: <YOUR_AWS_REGION>                  # e.g., us-west-2
  accountID: "<YOUR_AWS_ACCOUNT_ID>"         # e.g., "123456789012"

  # Platform profile
  profile: development

  # Essential modules only
  modules:
    observability: true
    dns: true
    compute: true
    metrics: true
    secrets: true
    logging: false

  # Observability
  observability:
    ampWorkspaceID: <YOUR_AMP_WORKSPACE_ID>
    ampRemoteWriteEndpoint: https://aps-workspaces.<YOUR_AWS_REGION>.amazonaws.com/workspaces/<YOUR_AMP_WORKSPACE_ID>/api/v1/remote_write
    retentionDays: 7

  # DNS
  dns:
    hostedZoneID: <YOUR_HOSTED_ZONE_ID>
    domainFilter: <YOUR_DOMAIN>              # e.g., dev.example.com
    zoneType: public
    policy: upsert-only

  # Compute (ARM for cost savings)
  compute:
    spotEnabled: true
    computeOptimized: false
    memoryOptimized: false
    armGraviton: true

  # Metrics
  metrics:
    highAvailability: false

  # Secrets
  secrets:
    secretsPrefix: "<YOUR_SECRETS_PREFIX>"   # e.g., "eks/dev"
    enableSecretsManager: true
    syncInterval: "6h"
